# Default initial positions for kinova_arm's ros2_control fake system

initial_positions:
  camera_joint: 0.0
  fore_arm_joint: 1.75
  half_arm_one_joint: -1.0
  half_arm_two_joint: 0.0
  left_finger_joint: 0.0
  right_finger_joint: 0.0
  shoulder_joint: 0.0
  spherical_wrist_one_joint: 0.0
  spherical_wrist_two_joint: 1.5