# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    kinova_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    kinova_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

kinova_arm_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - half_arm_one_joint
      - half_arm_two_joint
      - fore_arm_joint
      - spherical_wrist_one_joint
      - spherical_wrist_two_joint
      - camera_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
kinova_gripper_controller:
  ros__parameters:
    joints:
      - left_finger_joint
      - right_finger_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity