controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder_joint
      - half_arm_one_joint
      - half_arm_two_joint
      - fore_arm_joint
      - spherical_wrist_one_joint
      - spherical_wrist_two_joint
      - camera_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_finger_joint
      - right_finger_joint